### ISSUE TITLE
New installation

### ISSUE THREAD

**Issue by tischi** [embl-cba/DNA-FISH#21]
@babisgalouzis 

Could you please try this and report here whether it works?

https://github.com/embl-cba/DNA-FISH#installation

**Comment by babisgalouzis** [comment]
Installation works! However when I try to use the plugin, it reaches up to the ROIs for the background and then it drops the following error (Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 3574MB of 4288MB (83%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at de.embl.cba.fish.AnalyzeFISHSpotsUI.setSpotsChannelBackgrounds(AnalyzeFISHSpotsUI.java:313)
	at de.embl.cba.fish.AnalyzeFISHSpotsUI.<init>(AnalyzeFISHSpotsUI.java:106)
	at de.embl.cba.fish.AnalyzeFISHSpotsCommand.run(AnalyzeFISHSpotsCommand.java:23)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more


Could it be the sample image for any reason? Is the same image with the one I sent you, so you could possibly try with your installation. 
On the same kind of direction, could by any reason the M2 chip which I am using be a problem?

**Comment by babisgalouzis** [comment]
@tischi No it gives the same error. I also tried with an intel processor so it is not the apple silicon chip that could create a problem.
